// Code generated by mockery v2.38.0. DO NOT EDIT.

package insertotpauthdb

import (
	context "context"

	postgres "github.com/hansengotama/authentication-backend/internal/lib/postgres"
	mock "github.com/stretchr/testify/mock"
)

// MockInsertOTPAuthDBInterface is an autogenerated mock type for the InsertOTPAuthDBInterface type
type MockInsertOTPAuthDBInterface struct {
	mock.Mock
}

// InsertOTPAuth provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockInsertOTPAuthDBInterface) InsertOTPAuth(_a0 context.Context, _a1 postgres.SQLExecutor, _a2 InsertOTPAuthParam) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for InsertOTPAuth")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, postgres.SQLExecutor, InsertOTPAuthParam) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockInsertOTPAuthDBInterface creates a new instance of MockInsertOTPAuthDBInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInsertOTPAuthDBInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInsertOTPAuthDBInterface {
	mock := &MockInsertOTPAuthDBInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
