// Code generated by mockery v2.38.0. DO NOT EDIT.

package requestotpauthservice

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRequestOTPAuthServiceInterface is an autogenerated mock type for the RequestOTPAuthServiceInterface type
type MockRequestOTPAuthServiceInterface struct {
	mock.Mock
}

// RequestOTPAuth provides a mock function with given fields: _a0, _a1
func (_m *MockRequestOTPAuthServiceInterface) RequestOTPAuth(_a0 context.Context, _a1 RequestOTPAuthParam) (RequestOTPAuthRes, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for RequestOTPAuth")
	}

	var r0 RequestOTPAuthRes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, RequestOTPAuthParam) (RequestOTPAuthRes, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, RequestOTPAuthParam) RequestOTPAuthRes); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(RequestOTPAuthRes)
	}

	if rf, ok := ret.Get(1).(func(context.Context, RequestOTPAuthParam) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockRequestOTPAuthServiceInterface creates a new instance of MockRequestOTPAuthServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRequestOTPAuthServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRequestOTPAuthServiceInterface {
	mock := &MockRequestOTPAuthServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
