// Code generated by mockery v2.38.0. DO NOT EDIT.

package updateotpstatusauth

import (
	context "context"

	postgres "github.com/hansengotama/authentication-backend/internal/lib/postgres"
	mock "github.com/stretchr/testify/mock"
)

// MockUpdateOTPAuthStatusDBInterface is an autogenerated mock type for the UpdateOTPAuthStatusDBInterface type
type MockUpdateOTPAuthStatusDBInterface struct {
	mock.Mock
}

// UpdateOTPAuthStatus provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockUpdateOTPAuthStatusDBInterface) UpdateOTPAuthStatus(_a0 context.Context, _a1 postgres.SQLExecutor, _a2 UpdateOTPAuthStatusParam) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOTPAuthStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, postgres.SQLExecutor, UpdateOTPAuthStatusParam) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockUpdateOTPAuthStatusDBInterface creates a new instance of MockUpdateOTPAuthStatusDBInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdateOTPAuthStatusDBInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdateOTPAuthStatusDBInterface {
	mock := &MockUpdateOTPAuthStatusDBInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
